name: ğŸš€ Deploy to Hostinger

on:
  push:
    branches:
      - master   # Change this to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸšš Checkout code
        uses: actions/checkout@v3

      - name: ğŸ“¥ Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16   # Use the appropriate version

      - name: ğŸ“¦ Install dependencies
        run: npm install

      - name: ğŸ— Build CSS
        run: npm run css-build

      - name: ğŸ— Build 
        run: npm run build

      - name: ğŸ“‚ Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.HOSTINGER_SERVER }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          local-dir: build/
